feat: add pylint / black tests for pull requests
leaphy-robotics/leaphy-micropython pull request #17
Opened 2023-12-01 10:19 UTC by rmoesbergen

chore: reformat with black

2023-12-01 13:45 UTC, rmoesbergen commented on actuators/DCMotor.py
> +    def init(self, in_1: int, in_2: int, in_3: int, in_4: int, en_a: int, en_b: int):
```suggestion
    def __init__(self, in_1: int, in_2: int, in_3: int, in_4: int, en_a: int, en_b: int):
```

2023-12-02 09:11 UTC, koen1711 requested changes
Review what I marked

2023-12-02 09:11 UTC, koen1711 commented on actuators/rgbled.py
> +        Sets the color of the rgb-led
Maybe rename this

2023-12-02 09:13 UTC, Julius0530 approved these changes

2023-12-02 09:16 UTC, koen1711 approved these changes

2023-12-02 09:16 UTC, merged